product/urls.py
from .views import BrandDetail, BrandList, ProductList, ProductDetail,BrandDetail,queryset_debug
from django.urls import path


urlpatterns = [
    path("", ProductList.as_view()),
    path("debug",queryset_debug),
    path("brands/", BrandList.as_view()),
    path("<slug:slug>/", ProductDetail.as_view()),
    path("brands/<slug:slug>/", BrandDetail.as_view()),

]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from debug_toolbar.toolbar import debug_toolbar_urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('product.urls')),
]+ debug_toolbar_urls() 
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/models.py
import django
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from taggit.managers import TaggableManager
from django.utils.translation import gettext_lazy as _
from django.utils.text import slugify

# Create your models here.

FLAG_TYPES = (
    ('New','New'),
    ('Sale','Sale'),
    ('Feature','Feature')
)



class Product(models.Model):
    name = models.CharField(_("name"), max_length=120)
    flag = models.CharField(_("flag"), max_length=10,choices=FLAG_TYPES)
    price = models.FloatField(_("price"))
    image = models.ImageField(_("image"), upload_to='product')
    sku = models.IntegerField(_("sku"))
    subtitle = models.TextField(_("subtitle"), max_length=500)
    description = models.TextField(_("description"), max_length=50000)
    quantity = models.IntegerField(_("quantity"), default=0)
    brand = models.ForeignKey('Brand',verbose_name=_("brand"),related_name='product_brand',on_delete=models.SET_NULL,null=True)
    tags = TaggableManager()
    slug = models.SlugField(null=True, blank=True)

    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Product, self).save(*args, **kwargs)



class ProductImages(models.Model):
    product = models.ForeignKey(Product,verbose_name=_("product"),related_name='product_image',on_delete=models.CASCADE)
    image = models.ImageField(_("image"), upload_to='productimages')
    def __str__(self):
        return f"Image for {self.product.name}"

class Brand(models.Model):
    name = models.CharField(_("name"), max_length=100)
    image = models.ImageField(_("image"), upload_to='brand')
    slug = models.SlugField(null=True, blank=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Brand, self).save(*args, **kwargs)
        
    def __str__(self):
        return self.name

class Review(models.Model):
    user = models.ForeignKey(User,related_name='review_user',on_delete=models.SET_NULL,null=True)
    product = models.ForeignKey(Product,related_name='review_product',on_delete=models.CASCADE)
    review = models.TextField(max_length=500)
    rate = models.IntegerField(choices=[(i, i) for i in range(1, 6)])
    created_at = models.DateTimeField(default=timezone.now)

product/views.py
from statistics import quantiles
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView
from django.db.models import Q ,F ,Value
from .models import Product, ProductImages, Brand, Review
from django.db.models.aggregates import Min ,Max, Avg , Count



def queryset_debug(request):

    # data=Product.objects.select_related('brand')  #foreng key relations and one-to-one
    # data = data.prefetch_related('brand').all()  # prefetch_related for many-to-many or reverse foreign key relations
    #filter
    # data=Product.objects.filter(price__gt=20)
    # data=Product.objects.filter(price__gte=20)
    # data=Product.objects.filter(price__lt=20)
    # data=Product.objects.filter(price__lte=20)
    # data=Product.objects.filter(price__range=(15,20))
    # navigaion relation 
    # data=Product.objects.filter(brand__name='apple',quantity__gt=8)#and
    # data=Product.objects.filter(Q(brand__name='apple')|Q(quantity__gt=56))#or
    # data=Product.objects.filter(price=F('quantity'))
    # data=Product.objects.order_by('name')
    # data=Product.objects.values_list('name','price')
    # data=Product.objects.values('name','price')
    # data=Product.objects.distinct()
    # data=Product.objects.defer('slug')
    # data=Product.objects.aggregate(Max('quantity'))
    # add new field form cal
    data=Product.objects.annotate(price_e=F('price')*300)


    return render(request, 'product/debug.html',{"data":data})


class ProductList(ListView):
    model = Product
    

class ProductDetail(DetailView):
    model = Product
    def get_context_data(self, **kwargs): # v:r
        context = super().get_context_data(**kwargs)
        context['reviews'] = Review.objects.filter(product=self.object)
        context['related_products'] = Product.objects.filter(brand=self.object.brand).exclude(id=self.object.id)
        return context
    

class BrandList(ListView):
    model = Brand
    queryset=Brand.objects.annotate(product_count=Count('product_brand'))



class BrandDetail(ListView):
    model = Product
    template_name = 'product/brand_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["brand"]=Brand.objects.filter(slug=self.kwargs['slug']).annotate(product_count=Count('product_brand'))[0]
        return context
    
    def get_queryset(self):
        brand=Brand.objects.get(slug=self.kwargs['slug'])
        return super().get_queryset().filter(brand=brand)

product/templates/product/brand_detail.html
{% extends "base.html" %}
{% load static %}
{%block css%}
<link rel="stylesheet" href="{% static 'en/css/brand-single.css' %}">
{% endblock css %}
{%block body %} 
        <!--=====================================
                    BANNER PART START
        =======================================-->
        <section class="single-banner" style="background: url(images/single-banner.jpg) no-repeat center;">
            <div class="container">
                <h2>Brand Single</h2>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                    <li class="breadcrumb-item"><a href="brand-list.html">brand-list</a></li>
                    <li class="breadcrumb-item active" aria-current="page">brand-single</li>
                </ol>
            </div>
        </section>
        <!--=====================================
                    BANNER PART END
        =======================================-->


        <!--=====================================
                  BRAND SINGLE PART START
        =======================================-->
        <div class="brand-single">
            <a href="#"><img src="{{brand.image.url}}" alt="brand"></a>
            <a href="#"><h3>{{brand.name}}</h3></a>
            <ul>
                <li class="fas fa-star active"></li>
                <li class="fas fa-star active"></li>
                <li class="fas fa-star active"></li>
                <li class="fas fa-star active"></li>
                <li class="fas fa-star"></li>
                <li class="total">(163 ratings)</li>
            </ul>
            <p>({{brand.product_count}} items)</p>
        </div>
        <!--=====================================
                  BRAND SINGLE PART END
        =======================================-->


        <!--=====================================
                    SHOP PART START
        =======================================-->
        <section class="inner-section shop-part">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="top-filter">
                            <div class="filter-show">
                                <label class="filter-label">Show :</label>
                                <select class="form-select filter-select">
                                    <option value="1">12</option>
                                    <option value="2">24</option>
                                    <option value="3">36</option>
                                </select>
                            </div>
                            <div class="filter-short">
                                <label class="filter-label">Short by :</label>
                                <select class="form-select filter-select">
                                    <option selected>default</option>
                                    <option value="3">trending</option>
                                    <option value="1">featured</option>
                                    <option value="2">recommend</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row row-cols-2 row-cols-md-3 row-cols-lg-3 row-cols-xl-5">
                    {% for product in product_list %}
                    <div class="col">
                        <div class="product-card">
                            <div class="product-media">
                                <div class="product-label">
                                    <label class="label-text new">{{product.flag}}</label>
                                </div>
                                <button class="product-wish wish">
                                    <i class="fas fa-heart"></i>
                                </button>
                                <a class="product-image" href="product-video.html">
                                    <img src="{{product.image.url }}" style="height: 190px; width: 190px;" alt="product">
                                </a>
                                <div class="product-widget">
                                    <a title="Product Compare" href="compare.html" class="fas fa-random"></a>
                                    <a title="Product Video" href="https://youtu.be/9xzcVxSBbG8" class="venobox fas fa-play" data-autoplay="true" data-vbtype="video"></a>
                                    <a title="Product View" href="#" class="fas fa-eye" data-bs-toggle="modal" data-bs-target="#product-view"></a>
                                </div>
                            </div>
                            <div class="product-content">
                                <div class="product-rating">
                                    <i class="active icofont-star"></i>
                                    <i class="active icofont-star"></i>
                                    <i class="active icofont-star"></i>
                                    <i class="active icofont-star"></i>
                                    <i class="icofont-star"></i>
                                    <a href="product-video.html">(3)</a>
                                </div>
                                <h6 class="product-name">
                                    <a href="product-video.html">{{ product.name }}</a>
                                </h6>
                                <h6 class="product-price">
                                    <span>${{ product.price }}</span>
                                </h6>
                                <button class="product-add" title="Add to Cart">
                                    <i class="fas fa-shopping-basket"></i>
                                    <span>add</span>
                                </button>
                                <div class="product-action">
                                    <button class="action-minus" title="Quantity Minus"><i class="icofont-minus"></i></button>
                                    <input class="action-input" title="Quantity Number" type="text" name="quantity" value="1">
                                    <button class="action-plus" title="Quantity Plus"><i class="icofont-plus"></i></button>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="bottom-paginate">
                            <p class="page-info">Showing 12 of 60 Results</p>
                            <ul class="pagination">
                                <li class="page-item">
                                    <a class="page-link" href="#">
                                        <i class="fas fa-long-arrow-alt-left"></i>
                                    </a>
                                </li>
                                <li class="page-item"><a class="page-link active" href="#">1</a></li>
                                <li class="page-item"><a class="page-link" href="#">2</a></li>
                                <li class="page-item"><a class="page-link" href="#">3</a></li>
                                <li class="page-item">...</li>
                                <li class="page-item"><a class="page-link" href="#">60</a></li>
                                <li class="page-item">
                                    <a class="page-link" href="#">
                                        <i class="fas fa-long-arrow-alt-right"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--=====================================
                    SHOP PART END
        =======================================-->
        

        <!--=====================================
                    NEWSLETTER PART START
        =======================================-->
        <section class="news-part" style="background: url(images/newsletter.jpg) no-repeat center;">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-md-5 col-lg-6 col-xl-7">
                        <div class="news-text">
                            <h2>Get 20% Discount for Subscriber</h2>
                            <p>Lorem ipsum dolor consectetur adipisicing accusantium</p>
                        </div>
                    </div>
                    <div class="col-md-7 col-lg-6 col-xl-5">
                        <form class="news-form">
                            <input type="text" placeholder="Enter Your Email Address">
                            <button><span><i class="icofont-ui-email"></i>Subscribe</span></button>
                        </form>
                    </div>
                </div>
            </div>
        </section>
        <!--=====================================
                    NEWSLETTER PART END
        =======================================-->
{% endblock %}

product/templates/product/brand_list.html
{% extends "base.html" %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'en/css/brand-list.css' %}">
{% endblock css %}
{% block body %}
        <!--=====================================
                    BANNER PART START
        =======================================-->
        <section class="inner-section single-banner" style="background: url(images/single-banner.jpg) no-repeat center;">
            <div class="container">
                <h2>brand list</h2>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">brand-list</li>
                </ol>
            </div>
        </section>
        <!--=====================================
                    BANNER PART END
        =======================================-->


        <!--=====================================
                    BRAND LIST PART START
        =======================================-->
        <section class="inner-section">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="top-filter">
                            <div class="filter-show">
                                <label class="filter-label">Show :</label>
                                <select class="form-select filter-select">
                                    <option value="1">12</option>
                                    <option value="2">24</option>
                                    <option value="3">36</option>
                                </select>
                            </div>
                            <div class="filter-short">
                                <label class="filter-label">Short by :</label>
                                <select class="form-select filter-select isotope-select">
                                    <option value="*">show all</option>
                                    <option value=".vegetables">vegetables</option>
                                    <option value=".fruits">fruits</option>
                                    <option value=".drinks">drinks</option>
                                    <option value=".fishes">fishes</option>
                                    <option value=".meats">meats</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row row-cols-2 row-cols-md-3 row-cols-lg-4 row-cols-xl-5 isotope-items">
                   {% for brand in brand_list %}
                    <div class="col all vegetables">
                        <div class="brand-wrap">
                            <div class="brand-media">
                                <img src="{{ brand.image.url }}" alt="brand">
                                <div class="brand-overlay">
                                    <a href="{{brand.slug}}"><i class="fas fa-link"></i></a>
                                </div>
                            </div>
                            <div class="brand-meta">
                                <h4>{{ brand.name }}</h4>
                                <p>({{brand.product_count}} items)</p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="bottom-paginate">
                            <p class="page-info">Showing 12 of 60 Results</p>
                            <ul class="pagination">
                                <li class="page-item">
                                    <a class="page-link" href="#">
                                        <i class="fas fa-long-arrow-alt-left"></i>
                                    </a>
                                </li>
                                <li class="page-item"><a class="page-link active" href="#">1</a></li>
                                <li class="page-item"><a class="page-link" href="#">2</a></li>
                                <li class="page-item"><a class="page-link" href="#">3</a></li>
                                <li class="page-item">...</li>
                                <li class="page-item"><a class="page-link" href="#">60</a></li>
                                <li class="page-item">
                                    <a class="page-link" href="#">
                                        <i class="fas fa-long-arrow-alt-right"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--=====================================
                    BRAND LIST PART END
        =======================================-->


        <!--=====================================
                    NEWSLETTER PART START
        =======================================-->
        <section class="news-part" style="background: url(images/newsletter.jpg) no-repeat center;">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-md-5 col-lg-6 col-xl-7">
                        <div class="news-text">
                            <h2>Get 20% Discount for Subscriber</h2>
                            <p>Lorem ipsum dolor consectetur adipisicing accusantium</p>
                        </div>
                    </div>
                    <div class="col-md-7 col-lg-6 col-xl-5">
                        <form class="news-form">
                            <input type="text" placeholder="Enter Your Email Address">
                            <button><span><i class="icofont-ui-email"></i>Subscribe</span></button>
                        </form>
                    </div>
                </div>
            </div>
        </section>
        <!--=====================================
                    NEWSLETTER PART END
        =======================================-->
{% endblock %}

product/templates/product/debug.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1> debug</h1>

    <ul>
        {% for item in data %}
        <li>{{item}} - {{item.price}} </li>
        {%endfor%}
    </ul>

</body>

</html>